/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrs;

/**
 *
 * @author Alavi
 */
public class smainmenu extends javax.swing.JFrame {

    /**
     * Creates new form smainmenu
     */
    public smainmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sloginHeader = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        scrsHeader = new javax.swing.JLabel();
        StudentMainMenuLabel = new javax.swing.JLabel();
        NGBtn = new javax.swing.JButton();
        ManageProfileBtn = new javax.swing.JButton();
        FSBtn = new javax.swing.JButton();
        MCBtn = new javax.swing.JButton();

        sloginHeader.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        sloginHeader.setText("STUDENT LOGIN ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("APU STUDENT COURSE REGISTRATION SYSTEM");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrsHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        scrsHeader.setText("APU STUDENT COURSE REGISTRATION SYSTEM");

        StudentMainMenuLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        StudentMainMenuLabel.setText("STUDENT MAIN MENU");

        NGBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NGBtn.setText("NEW REGISTRATION");

        ManageProfileBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ManageProfileBtn.setText("MANAGE PROFILE");
        ManageProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageProfileBtnActionPerformed(evt);
            }
        });

        FSBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        FSBtn.setText("FEE STATEMENT");

        MCBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MCBtn.setText("MY COURSES");
        MCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(scrsHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(StudentMainMenuLabel)
                        .addGap(217, 217, 217))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NGBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManageProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FSBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(271, 271, 271))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(scrsHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentMainMenuLabel)
                .addGap(49, 49, 49)
                .addComponent(ManageProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(NGBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(MCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(FSBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageProfileBtnActionPerformed
        
        {
            sstudentprofile info=new sstudentprofile();
            info.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_ManageProfileBtnActionPerformed

    private void MCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCBtnActionPerformed
         
        {
            smycourses info=new smycourses();
            info.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_MCBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(smainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(smainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(smainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(smainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new smainmenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FSBtn;
    private javax.swing.JButton MCBtn;
    private javax.swing.JButton ManageProfileBtn;
    private javax.swing.JButton NGBtn;
    private javax.swing.JLabel StudentMainMenuLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel scrsHeader;
    private javax.swing.JLabel sloginHeader;
    // End of variables declaration//GEN-END:variables
}
